djangovue/account/urls.py
from django.urls import path
from .views import user_data,profile,register
app_name='account'
urlpatterns = [
    path('user_data/', user_data, name="user_data"),
    path('profile/', profile, name="profile"),
    path('register/', register, name="register")
]

djangovue/comment/urls.py
from django.urls import path
from .views import add, index, update, contact

app_name='comment'
urlpatterns = [
    path('', index, name="index"),
    path('add', add, name="add"),
    path('contact', contact, name="contact"),
    path('update/<int:pk>', update, name="update"),
]

djangovue/djangovue/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('listelement.urls')),
    path('comment/',include('comment.urls') ),
    path("accounts/", include("account.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

djangovue/listelement/urls.py
from django.urls import path
from rest_framework import routers
from .viewsets import ElementViewSet, CategoryViewSet, TypeViewSet, CommentViewSet


route = routers.SimpleRouter()
route.register('element', ElementViewSet)
route.register('type', TypeViewSet)
route.register('category', CategoryViewSet)
route.register('comment', CommentViewSet)

urlpatterns = route.urls

djangovue/account/models.py
from django.db import models

# Create your models here.

djangovue/comment/models.py
from django.db import models
from listelement.models import Element

# Create your models here.
class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    element = models.ForeignKey(Element,related_name='comments', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return 'Comentario #{}'.format(self.id)

class TypeContact(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    SEX = (
        ('M','Masculino'),
        ('F','Femenino'),
        ('N','No binario')
    )
    name= models.CharField(max_length=255)
    surname= models.CharField(max_length=255)
    email = models.CharField(max_length=70)
    phone = models.CharField(max_length=13)
    date_birth = models.DateField()
    document = models.FileField(upload_to='uploads/contact')
    sex = models.CharField(max_length=1,choices=SEX,default='N')
    type_contact = models.ForeignKey(TypeContact, on_delete=models.CASCADE, default=1)



    

djangovue/listelement/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length= 255)
    url_clean = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Type(models.Model):
    title = models.CharField(max_length= 255)
    url_clean = models.CharField(max_length=255)
    def __str__(self):
        return self.title


class Element(models.Model):
    title = models.CharField(max_length= 255)
    url_clean = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,decimal_places=2, default=6.10)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

djangovue/comment/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment, TypeContact


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': Textarea(attrs={
                'class':'form-input'
            })
        }
    def save(self, commit=True):
        instance = super(CommentForm, self).save(commit=commit)
        if(commit):
            instance.save()

from django import forms 
from django.core.validators import MinLengthValidator,EmailValidator

class ContactForm(forms.Form):
    SEX = (
        ('M','Masculino'),
        ('F','Femenino'),
        ('N','No binario')
    )
    #name = forms.CharField(label="Nombre", required=True, disabled=False, help_text="Aquí va tu nombre", max_length=10, min_length=2)
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}) ,label="Nombre", validators=[MinLengthValidator(2, message="Muy corto! (minimo %(limit_value)d) actual %(show_value)d")])
    surname = forms.CharField(label="Apellido", required=False , max_length=10, min_length=2)
    #phone = forms.RegexField(label='Telefono', regex='\(\w{3}\)\w{3}-\w{4}')
    phone = forms.CharField(label='Telefono',initial="999999999")
    date_birth = forms.DateField(widget=forms.DateInput(),label='Fecha de nacimiento',initial="9/7/1981")
    email = forms.EmailField(label="Correo",initial="loquesea@gmial.com")
    #mail = forms.CharField(label="Email", validators=[EmailValidator("No es un email válido")])
    #type_contact = forms.ChoiceField(label="Tipo de contacto", choices=CHOICE, initial=2)
    type_contact = forms.ModelChoiceField(label="Tipo de contacto", queryset=TypeContact.objects.all())
    sex = forms.ChoiceField(label="Sexo", choices=SEX, initial="N")
    document = forms.FileField(label="Documento",required=False)
    terms = forms.BooleanField(label="Condiciones de servicio")

djangovue/account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def user_data(request):
    print(request.user.username)
    return render(request,'account/user_data.html')

@login_required
def profile(request):
    return render(request,'account/profile.html')


def register(request):
    form = UserCreationForm()
    return render(request,'account/register.html',{'form':form})

djangovue/comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Comment,Contact
from .forms import CommentForm, ContactForm

# Create your views here.
def index(request):
    comments = Comment.objects.all()
    return render(request,'comment/index.html', {
        'comments':comments
    })


def add(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comment:index')
    else:
        form = CommentForm()

    

    return render(request,'comment/add.html', {
        'form':form
    })

def update(request, pk):

    comment = get_object_or_404(Comment, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)

        print(form.errors.as_json())
        if form.is_valid():
            form.save(commit=False)
            return redirect('comment:update',pk=comment.id)
    else:
        form = CommentForm(instance=comment)

    return render(request,'comment/update.html', {
        'form':form,
        'comment':comment
    })


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)
        if form.is_valid():
            print('Nombre: '+form.cleaned_data['name'])
            contact = Contact()
            contact.name = form.cleaned_data['name']
            contact.surname = form.cleaned_data['surname']
            contact.phone = form.cleaned_data['phone']
            contact.email = form.cleaned_data['email']
            contact.date_birth = form.cleaned_data['date_birth']
            contact.sex = form.cleaned_data['sex']
            contact.type_contact = form.cleaned_data['type_contact']
            if 'document' in request.FILES:
                contact.document = request.FILES['document']
            contact.save()

            messages.add_message(request, messages.INFO, 'Contacto recibido')
            return redirect('comment:index')
            #form.save()
            #return redirect('indexcomment')
    else:
        form = ContactForm()
    return render(request,'comment/contact.html', {
        'form':form
    })
    

djangovue/account/templates/account copy/user_data.html
{% extends "comment/base.html" %} {% comment %} Aprovechamos la el template del app comment {% endcomment %}
{% load bootstrap %}

{% block content %}
{% if user.is_authenticated %}
  <ul>
    <li><strong>Usuario: </strong>{{user.username}}</li>
    <li><strong>Email: </strong>{{user.email}}</li>
</ul>
{% else %}
    <p><a href="{% url 'login' %}">Login</a></p>
{% endif %}





{% endblock %}

djangovue/comment/templates/comment/add.html
{% extends "comment/base.html" %}
{% block content %}
    <form action="{% url 'comment:add' %}" method="post">
        {% csrf_token %}
        {{ form.text }}
        <input type="submit" value="Enviar">
    </form>
   <style>
    .form-input {
        width: 100%;
    }
   </style>
{% endblock %}

djangovue/comment/templates/comment/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactos</title>
    {% load static %}
    {% load bootstrap %}

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    {% include "comment/partials/header.html" %}
    <div class="container my-3">
        {% block content %}
      
        {% endblock %}
    </div>
    {% include "comment/partials/footer.html" %}
    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

djangovue/comment/templates/comment/base_user_account.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactos</title>
    {% load static %}
    {% load bootstrap %}

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/user.style.css' %}">
</head>
<body>
<div class="sidenav">
         <div class="login-main-text">
            <h2>Application<br> Login Page</h2>
            <p>Login or register from here to access.</p>
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            {% block content %}
      
            {% endblock %}
         </div>
      </div>
    <div class="container my-3">
        
    </div>

    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

djangovue/comment/templates/comment/contact.html
{% extends "comment/base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container mt-3">
  {% if messages %}

      {% for m in messages %}
        <div class="alert {% if m.tags %}alert-{{m.tags}}{% endif %}">{{m}}</div>
      {% endfor %}

  {% endif %}
  <div class="card">
    <div class="card-header">
      Formulario de contacto
    </div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors  %}
            <div class="alert alert-danger" role="alert">
              <strong>{{field.name}}: </strong>{{ error }}
            </div>
              
            {% endfor %}\
          {% endfor %}
        {% endif %}
        

        {{ form|bootstrap }}
        <input type="submit" class="btn btn-primary" value="Enviar">
    </form>
    </div>
  </div>
  
</div>



{% endblock %}
    

djangovue/comment/templates/comment/index.html
{% extends "comment/base.html" %}
{% block content %}
    {% if comments %}
    <ul>
        {% for c in comments %}
            <li>\
                {{ c.text }}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No hay comentarios</p>
    {% endif %}
{% endblock %}

djangovue/comment/templates/comment/partials/alert.html
{% if messages %}

      {% for m in messages %}
        <div class="alert {% if m.tags %}alert-{{m.tags}}{% endif %}">{{m}}</div>
      {% endfor %}

{% endif %}


{% if msj %}
<div class="alert {% if tag %} alert-{{tag}} {% else %} alert-info {% endif %}">{{msj}}</div>
{% endif %}

djangovue/comment/templates/comment/partials/footer.html
<!-- Footer -->
<footer class="page-footer font-small bg-primary text-white">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 
    <a class="text-secondary" href="{% url 'comment:contact' %}"> Contact</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

djangovue/comment/templates/comment/partials/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'comment:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'comment:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

djangovue/comment/templates/comment/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django</title>
</head>
<body>
    <form action="{% url 'updatecomment' comment.id %}" method="post">
        {% csrf_token %}
        {{ form.text }}
        <input type="submit" value="Enviar">
    </form>
   <style>
    .form-input {
        width: 100%;
    }
   </style>
</body>
</html>